# This file was generated by GoReleaser. DO NOT EDIT.
cask "slink" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "ba8b564981e34b276470aa2b38c6938e220a5fc852e7b632e16e661c48d0f0f3"
      url "https://github.com/lftherios/session-link/releases/download/v#{version}/slink_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a4983b600e6d00a8122256af9a1df6a2913c71ff2ea0ef72c9688a7a5714bcc7"
      url "https://github.com/lftherios/session-link/releases/download/v#{version}/slink_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dbee7ae55b12c02cf0f4334f64292923ce811b373970c73254634b6b2b02bdf4"
      url "https://github.com/lftherios/session-link/releases/download/v#{version}/slink_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7d18c91fd3145085781f8d137b18069b6991962284845a2a7aa5979937ddf2f1"
      url "https://github.com/lftherios/session-link/releases/download/v#{version}/slink_#{version}_linux_amd64.tar.gz"
    end
  end

  name "slink"
  desc "Capture LLM sessions locally, publish the ones worth sharing"
  homepage "https://session.link"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slink"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slink"]
  end

  # No zap stanza required
end
