# This file was generated by GoReleaser. DO NOT EDIT.
cask "slink" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "4833076e73e0b1327d50bd6e8cd91e9b58ac40e90f5a36140842435d40675fdf"
      url "https://github.com/lftherios/session-link/releases/download/v#{version}/slink_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "160d75c4e970304ec733fbd2e882a1142de61b16582d85cb0380353080dae95d"
      url "https://github.com/lftherios/session-link/releases/download/v#{version}/slink_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7de2da722db9ef867baccd62e3d402ad822ac26019e91c27d2c327f41a0f22a2"
      url "https://github.com/lftherios/session-link/releases/download/v#{version}/slink_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3cb901399a84e81a6efcee996b44b80a77ba7e165dfdc8665aa154f45ea0f261"
      url "https://github.com/lftherios/session-link/releases/download/v#{version}/slink_#{version}_linux_arm64.tar.gz"
    end
  end

  name "slink"
  desc "Capture LLM sessions locally, publish the ones worth sharing"
  homepage "https://session.link"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slink"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slink"]
  end

  # No zap stanza required

end
