# This file was generated by GoReleaser. DO NOT EDIT.
cask "slink" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "82b8fb6e095045087bc6b58bade390f07fd219361096d12079aadf8076f52d30"
      url "https://github.com/lftherios/session-link/releases/download/v#{version}/slink_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0b8cc79305c3e738ca65c116713fa35efe34740bf82a85c5bddcf4ed9238a4e1"
      url "https://github.com/lftherios/session-link/releases/download/v#{version}/slink_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ea9a18b0a7330b77ff4dfc6b3ca3b87e5fe90ac0bfad2f591614b533ad9117b6"
      url "https://github.com/lftherios/session-link/releases/download/v#{version}/slink_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7fbbf61ca3326c911263d9e3cccde53937478d770067277215c06d537f7f520a"
      url "https://github.com/lftherios/session-link/releases/download/v#{version}/slink_#{version}_linux_amd64.tar.gz"
    end
  end

  name "slink"
  desc "Capture LLM sessions locally, publish the ones worth sharing"
  homepage "https://session.link"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slink"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slink"]
  end

  # No zap stanza required
end
